###############################################
#
# Makefile - for cleaning up simpl/lib 
#
#$Log: Makefile,v $
#Revision 1.1.1.1  2005/03/27 11:50:33  paul_c
#Initial import
#
#Revision 1.4  2003/04/23 20:41:03  root
#added support for dynamic libraries
#
#Revision 1.3  2002/12/02 15:56:50  root
#v2.0 changes
#
#Revision 1.2  2000/10/13 14:15:50  root
#-> SIMPL_HOME
#
#Revision 1.1  1999/09/09 14:20:48  root
#Initial revision
#
#Revision 1.2  1999/02/04 16:39:40  root
#cleanup
#
#Revision 1.1  1998/07/31 21:33:52  root
#Initial revision
#
#
#
###############################################
#===============================================
# Default targets
# This makefile is only used to clobber specific
# files in the fc/lib directory
#===============================================
clobber:\
     title
	@-rm libfctclx.*
	@-rm libsimpl.*
	@-rm libsimpllog.*
	@-rm libsimplmisc.*
	@echo simpl/lib clobber

title:
	@echo simpl/lib clobber starting
